name: GitHub Actions Demo
on: 
    push: 
      branches: 
        - main
      paths-ignore: '.github/'
    pull_request:
      branches:
        - main
    schedule:
        - cron: '15 6 * * SUN'
    workflow_dispatch:

jobs:
  display-variables:
    name: 'Build'
    runs-on: 'ubuntu-latest'
    steps:
        - run: |
            echo '${github.action}'
            echo '${github.action_ref}'
            echo tree
                
    
  
        
    
