name: CI Build for Docker Action
on:
  push:
    branches:
      - main
    paths: 
      - ./hello-world-docker-action/**
      - ./.github/worflows/hello-world-docker-ci.yml      
  workflow_dispatch:
  
jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0

      - name: Run my own container action
        id: hello-action
        uses: ./hello-world-docker-action
        with:
          who-to-greet: '@StefanHuber'

      - name: Output time set in the container
        run: echo "Action runs at ${{ steps.hello-action.outputs.time }}"
